default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE", "warranty_manager_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_DATABASE", "warranty_manager_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
