default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER", "postgresql") %>
  encoding: <%= ENV.fetch("DB_ENCODING", "unicode") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE", "warranty_manager_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_DATABASE", "warranty_manager_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE", "dbwarranty") %>
  username: <%= ENV.fetch("DB_USERNAME", "dbwarranty_user") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
